### ISSUE TITLE
Suggest update example to ESP-IDF 5.2.1 + esp-zboss-lib + esp-zigbee-lib "~1.2.1" which currently are very latest versions.

### ISSUE THREAD

**Issue by Hedda** [luar123/esphome_zb_sensor#12]
As per https://github.com/luar123/esphome_zb_sensor/issues/6 but not quite implemented in https://github.com/luar123/esphome_zb_sensor/commit/eb560655323ae8df8ae987efc279aed4fa413e6e suggest update IDF Component Manager Manifest File to the latest stable releases:

https://github.com/luar123/esphome_zb_sensor/blob/master/idf_component.yml

```
## IDF Component Manager Manifest File
dependencies:
  espressif/esp-zigbee-lib: "~1.2.1"
  espressif/esp-zboss-lib: "~1.2.1"
  ## Required IDF version
  idf:
    version: ">=5.2.1"
```

Suggest update this example to ESP-IDF release v5.2.1 + esp-zboss-lib + esp-zigbee-lib "~1.2.1" which currently are very latest versions.

ESP-IDF Release v5.2.1 is currently the latest stable IDF release:

https://github.com/espressif/esp-idf/releases/tag/v5.2.1

esp-zigbee-lib 1.2.1 is currently the latest stable esp-zigbee-lib release:

https://components.espressif.com/components/espressif/esp-zigbee-lib

esp-zboss-lib 1.2.1 is currently the latest stable esp-zboss-lib release:

https://components.espressif.com/components/espressif/esp-zboss-lib
